# Generated by Django 3.2.19 on 2023-05-25 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('press', '0001_initial'),
        ('editors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('create_time', models.DateTimeField(auto_now=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='删除', verbose_name='删除')),
                ('id', models.AutoField(help_text='主键id', primary_key=True, serialize=False, verbose_name='主键id')),
                ('name', models.CharField(help_text='书名', max_length=20, unique=True, verbose_name='书名')),
                ('press_time', models.CharField(help_text='出版时间', max_length=20, verbose_name='出版时间')),
                ('desc', models.TextField(help_text='简要描述', verbose_name='简要描述')),
                ('author', models.ForeignKey(help_text='所属作者', on_delete=django.db.models.deletion.CASCADE, to='editors.editors', verbose_name='所属作者')),
                ('publish_house', models.ForeignKey(help_text='所属出版社', on_delete=django.db.models.deletion.CASCADE, to='press.press', verbose_name='所属出版社')),
            ],
            options={
                'verbose_name': '图书信息',
                'verbose_name_plural': '图书信息',
                'db_table': 'tb_books',
            },
        ),
    ]
