# Generated by Django 3.2.19 on 2023-05-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('create_time', models.DateTimeField(auto_now=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='删除', verbose_name='删除')),
                ('id', models.AutoField(help_text='主键id', primary_key=True, serialize=False, verbose_name='主键id')),
                ('name', models.CharField(help_text='出版社名', max_length=20, verbose_name='出版社名')),
                ('address', models.CharField(help_text='地址', max_length=50, verbose_name='地址')),
                ('desc', models.TextField(help_text='简要描述', verbose_name='简要描述')),
            ],
            options={
                'verbose_name': '出版社',
                'verbose_name_plural': '出版社',
                'db_table': 'tb_press',
            },
        ),
    ]
