# Generated by Django 3.2.19 on 2023-06-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholars',
            fields=[
                ('id', models.AutoField(help_text='主键id', primary_key=True, serialize=False, verbose_name='主键id')),
                ('name', models.CharField(help_text='姓名', max_length=20, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], help_text='性别', verbose_name='性别')),
                ('age', models.IntegerField(help_text='年龄', verbose_name='年龄')),
                ('address', models.CharField(help_text='祖籍', max_length=50, verbose_name='祖籍')),
                ('education_level', models.IntegerField(choices=[(1, '博士'), (2, '研究生'), (3, '本科'), (4, '大专'), (5, '高中'), (6, '初中'), (7, '小学'), (8, '其他')], help_text='学历', verbose_name='学历')),
                ('edu_type', models.IntegerField(choices=[(1, '全日制'), (2, '非全日制'), (3, '国外留学')], help_text='学历类型', verbose_name='学历类型')),
                ('personal_experience', models.TextField(help_text='个人经历', verbose_name='个人经历')),
            ],
            options={
                'verbose_name': '学技能的人',
                'verbose_name_plural': '学技能的人',
                'db_table': 'tb_scholars',
            },
        ),
    ]
