# Generated by Django 3.2.19 on 2023-05-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editors',
            fields=[
                ('create_time', models.DateTimeField(auto_now=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='删除', verbose_name='删除')),
                ('id', models.AutoField(help_text='主键id', primary_key=True, serialize=False, verbose_name='主键id')),
                ('name', models.CharField(help_text='作者名', max_length=10, verbose_name='作者名')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '其他')])),
                ('age', models.IntegerField(help_text='年龄', verbose_name='年龄')),
                ('address', models.CharField(help_text='出生地', max_length=20, verbose_name='出生地')),
                ('desc', models.TextField(help_text='个人简介', verbose_name='个人简介')),
            ],
            options={
                'verbose_name': '作者表信息',
                'verbose_name_plural': '作者表信息',
                'db_table': 'tb_editors',
            },
        ),
    ]
