# Generated by Django 3.2.19 on 2023-05-25 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('figures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Martails',
            fields=[
                ('create_time', models.DateTimeField(auto_now=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='删除', verbose_name='删除')),
                ('id', models.AutoField(help_text='主键id', primary_key=True, serialize=False, verbose_name='主键id')),
                ('name', models.CharField(help_text='技能名', max_length=20, verbose_name='技能名')),
                ('learn_time', models.IntegerField(help_text='修炼时间', verbose_name='修炼时间')),
                ('power_value', models.IntegerField(help_text='武力值', verbose_name='武力值')),
                ('desc', models.TextField(help_text='简要描述', verbose_name='简要描述')),
                ('people', models.ForeignKey(help_text='大侠名', on_delete=django.db.models.deletion.CASCADE, to='figures.figures', verbose_name='大侠名')),
            ],
            options={
                'verbose_name': '技能信息',
                'verbose_name_plural': '技能信息',
                'db_table': 'tb_martails',
            },
        ),
    ]
