# Generated by Django 3.2.19 on 2023-05-25 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figures',
            fields=[
                ('create_time', models.DateTimeField(auto_now=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='删除', verbose_name='删除')),
                ('id', models.AutoField(help_text='主键id', primary_key=True, serialize=False, verbose_name='主键id')),
                ('name', models.CharField(help_text='姓名', max_length=20, unique=True, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '其他')])),
                ('age', models.IntegerField(help_text='年龄', verbose_name='年龄')),
                ('nation', models.CharField(help_text='所属国家', max_length=20, verbose_name='所属国家')),
                ('desc', models.TextField(help_text='简要描述', verbose_name='简要描述')),
                ('title', models.ForeignKey(help_text='所属图书', on_delete=django.db.models.deletion.CASCADE, to='books.books', verbose_name='所属图书')),
            ],
            options={
                'verbose_name': '武侠人物表',
                'verbose_name_plural': '武侠人物表',
                'db_table': 'tb_figures',
            },
        ),
    ]
