# Generated by Django 3.2.19 on 2023-06-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figures',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '其他')], help_text='性别', verbose_name='性别'),
        ),
    ]
